// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Models;
using System;

namespace TodoApi.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Models.Gren", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Navn");

                    b.Property<int>("Poeng");

                    b.HasKey("Id");

                    b.ToTable("Gren");
                });

            modelBuilder.Entity("Models.Kamp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GrenId");

                    b.Property<int?>("KonkurranseId");

                    b.Property<string>("Sted");

                    b.HasKey("Id");

                    b.HasIndex("GrenId");

                    b.HasIndex("KonkurranseId");

                    b.ToTable("Kamper");
                });

            modelBuilder.Entity("Models.Konkurranse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Navn");

                    b.HasKey("Id");

                    b.ToTable("Konkurranse");
                });

            modelBuilder.Entity("Models.Lag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Navn");

                    b.HasKey("Id");

                    b.ToTable("Lag");
                });

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Models.Kamp", b =>
                {
                    b.HasOne("Models.Gren", "Gren")
                        .WithMany()
                        .HasForeignKey("GrenId");

                    b.HasOne("Models.Konkurranse", "Konkurranse")
                        .WithMany()
                        .HasForeignKey("KonkurranseId");
                });
#pragma warning restore 612, 618
        }
    }
}
